version: '3.8'

services:
  app:
    build:
      context: .
    image: ks-it-school:latest
    environment:
      APP_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ks_it_school
      SPRING_DATASOURCE_USERNAME: menghor
      SPRING_DATASOURCE_PASSWORD: Hour1819
      SPRING_PROFILES_ACTIVE: prod
      LOG_PATH: /opt/logs
    ports:
      - "8080:8080"
    volumes:
      - /opt/logs:/opt/logs
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temp_admin_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    environment:
      - NGINX_SERVER_NAME=localhost
      - NGINX_MAX_BODY=10M
      - HOST=app
      - PORT=8080
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: