spring:
  application:
    name: ks-it-school
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://143.198.93.97:5434/ks_it_school
    username: menghor
    password: Hour1819
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

  mvc:
    static-path-pattern: /static/**
    web:
      resources:
        static-locations: classpath:/static/,classpath:/public/

# Logging configuration
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.menghor.ksit: INFO
    org.springframework: INFO
    org.hibernate: WARN


server:
  port: ${APP_PORT:8080}

jwt:
  secret:
    key: da2bd42bef8f9f957d647ed13571d35b59c7055fb723eacdb05154878da17d77d3180385fc232cab38bded0fc7dbda0d439cc275e91164ade266d64d50633bc7
  expiration-min: 14400  # 10 days in minutes

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
    enabled: true
  packagesToScan: com.menghor.ksit